metadata:
  logo: "/assets/supranim.png"
  title: "Supranim Documentation"
  description: "Documentation for Supranim, the modern Web framework for building web applications with Nim lang"
  keywords: ["supranim", "nim", "web framework", "documentation", "framework", "booyaka docs"]

appearance:
  show_theme_switcher: true
  default_theme: "system"
  show_toggle_left_sidebar: true
  show_toggle_right_sidebar: true
  container_width: "col-lg-10 mx-auto"
  content_width: "col-lg-7"
  background_noise_opacity: 0.03

git:
  enable_versioning: false
  enable_contributors_info: false

header:
  search:
    enable: true
    index_meta_data: true
    index_page_titles: true

content:
  allowedRawHtmlTags:
    - "b"
    - "i"
    - "strong"
    - "em"
    - "a"
    - "p"
    - "ul"
    - "ol"
    - "li"

  showLastUpdated: true
  lastDateUpdatedFormat: "yyyy-MM-dd HH:mm:ss"
  enableAutoFormatLinks: true
  bottom_navigation: true
  codeHighlightTheme: "default"

  share_ai_buttons: true
  share_buttons_ai_providers:
    - label: "ChatGPT"
      url: "https://chat.openai.com/share?text={content}"
      description: "Share with ChatGPT"
    - label: "Claude"
      url: "https://claude.ai/share?text={content}"
      description: "Share with Claude"

navbar:
  - title: "Home"
    url: "/"
    icon: ""
  - title: "Check it out on GitHub"
    url: "https://github.com/supranim/supranim"
    icon: "github"

sidebar_navigation:
  - name: "Getting Started"
    items:
      - title: "Introduction"
        url: "/"

      - title: "Installation"
        url: "/install"

      - title: "Starter Kits"
        url: "/starter-kits"

      - title: "Supra CLI"
        url: "/supra"

      - title: "Deployment"
        url: "/deployment"

      - title: "Dependencies"
        url: "/dependencies"

      - title: "License"
        url: "/license"

  - name: "The Concept"
    items:
      - title: "Project structure"
        url: "/concept/project-structure"

      - title: "Configuration"
        url: "/concept/configuration"

      - title: "Service Providers"
        url: "/concept/providers"
  
  - name: "Basics"
    items:
      - title: "Routing"
        url: "/basics/routing"

      - title: "Middleware"
        url: "/basics/middleware"
        
      - title: "Controllers"
        url: "/basics/controller"

      - title: "Templates"
        url: "/basics/templates"

      - title: "Validation"
        url: "/basics/validation"

  - name: "Database"
    items:
      - title: "Models"
        url: "/database/models"

      - title: "Migrations"
        url: "/database/migrations"

      - title: "Query Builder"
        url: "/database/queries"

      - title: "Collection"
        url: "/database/collection"

extra_sections:
  left_sidebar:
    - content: |
        <div class="card border-2 rounded-4" style="border-style: dotted;">
          <div class="card-body small p-2 lh-sm justify-content-center d-flex align-items-center user-select-none">
            <div class="bg-warning flex-shrink-0 rounded-pill p-1 me-2">
              <img class="img-fluid" src="/assets/bug-icon.png" width="32px" height="32px" alt="Bug Icon">
            </div>
            <p class="mb-0 small d-inline">
              <strong>Found a bug?</strong><br>Create a new issue on <a href="https://github.com/supranim/supranim/issues" class="text-link d-inline-block bg-dark" target="_blank">GitHub</a>
            </p>
          </div>
        </div>
  right_sidebar:
    - content: |
        <div class="card border-2 rounded-4 me-3" style="border-style: dotted;">
          <div class="card-body small p-5 lh-sm user-select-none">
            <img class="img-fluid" src="https://www.hetzner.com/_resources/themes/hetzner/images/logo/hetzner-logo.svg?m=1764328696" width="100%" alt="Hetzner Logo">
            <p class="mt-3">
              Get € 20.00 free credit on Hetzner Cloud with our link!<br>
            </p>
            <p class="mb-0 text-center">
              <a href="https://hetzner.cloud/?ref=Hm0mYGM9NxZ4" class="btn btn-sm py-1 rounded-pill bg-dark d-inline-block" target="_blank">Go to Hetzner Cloud</a>
            </p>
          </div>
        </div>

footer:
  text: ""
  links:
    - title: "GitHub"
      url: "https://github.com/example"
      icon: "icon-brand-github"